#!/bin/bash
# ec.sh

# Standard Exit Codes
EXIT_SUCCESS=0
EXIT_FAILURE=1
EXIT_INVALID_USAGE=2

# Configuration errors (3-9)
EXIT_CONFIG_ERROR=3
EXIT_MISSING_DEPENDENCY=4
EXIT_PERMISSION_DENIED=5
EXIT_INVALID_CONFIG=6
EXIT_CONFIG_NOT_FOUND=7
EXIT_INITIALIZATION_FAILED=8
EXIT_ENVIRONMENT_ERROR=9

# File/Directory errors (10-19)
EXIT_FILE_NOT_FOUND=10
EXIT_DIRECTORY_NOT_FOUND=11
EXIT_FILE_READ_ERROR=12
EXIT_FILE_WRITE_ERROR=13
EXIT_DISK_FULL=14
EXIT_IO_ERROR=15
EXIT_FILE_EXISTS=16
EXIT_INVALID_PATH=17
EXIT_SYMLINK_ERROR=18
EXIT_MOUNT_ERROR=19

# Network errors (20-29)
EXIT_NETWORK_ERROR=20
EXIT_CONNECTION_FAILED=21
EXIT_CONNECTION_TIMEOUT=22
EXIT_DNS_ERROR=23
EXIT_DOWNLOAD_FAILED=24
EXIT_SSL_ERROR=25
EXIT_AUTHENTICATION_FAILED=26
EXIT_PROXY_ERROR=27
EXIT_FIREWALL_BLOCKED=28
EXIT_NETWORK_UNREACHABLE=29

# Database errors (30-39)
EXIT_DATABASE_ERROR=30
EXIT_DATABASE_CONNECTION_FAILED=31
EXIT_DATABASE_QUERY_FAILED=32
EXIT_DATABASE_SCHEMA_ERROR=33
EXIT_DATABASE_LOCK_ERROR=34
EXIT_DATABASE_TIMEOUT=35
EXIT_DATABASE_PERMISSION=36
EXIT_DATABASE_NOT_FOUND=37
EXIT_DATABASE_CORRUPTION=38
EXIT_DATABASE_MIGRATION_FAILED=39

# Service errors (40-49)
EXIT_SERVICE_ERROR=40
EXIT_SERVICE_NOT_RUNNING=41
EXIT_SERVICE_START_FAILED=42
EXIT_SERVICE_STOP_FAILED=43
EXIT_PROCESS_NOT_FOUND=44
EXIT_PROCESS_KILL_FAILED=45
EXIT_DAEMON_ERROR=46
EXIT_LOCK_FILE_EXISTS=47
EXIT_PID_FILE_ERROR=48
EXIT_SERVICE_TIMEOUT=49

# Validation errors (50-59)
EXIT_VALIDATION_ERROR=50
EXIT_DATA_FORMAT_ERROR=51
EXIT_CHECKSUM_MISMATCH=52
EXIT_DATA_CORRUPTION=53
EXIT_PARSE_ERROR=54
EXIT_ENCODING_ERROR=55
EXIT_JSON_ERROR=56
EXIT_XML_ERROR=57
EXIT_CSV_ERROR=58
EXIT_REGEX_ERROR=59

# Security errors (60-69)
EXIT_SECURITY_ERROR=60
EXIT_UNAUTHORIZED=61
EXIT_FORBIDDEN=63
EXIT_AUTHENTICATION_ERROR=64
EXIT_CERTIFICATE_ERROR=65
EXIT_ENCRYPTION_ERROR=66
EXIT_SIGNATURE_ERROR=67
EXIT_PRIVILEGE_ESCALATION=68
EXIT_SECURITY_POLICY_VIOLATION=69

# Resource errors (70-79)
EXIT_RESOURCE_ERROR=70
EXIT_MEMORY_ERROR=71
EXIT_CPU_LIMIT_EXCEEDED=72
EXIT_TIME_LIMIT_EXCEEDED=73
EXIT_FILE_LIMIT_EXCEEDED=74
EXIT_QUOTA_EXCEEDED=75
EXIT_RESOURCE_BUSY=76
EXIT_RESOURCE_UNAVAILABLE=77
EXIT_INSUFFICIENT_RESOURCES=78
EXIT_RESOURCE_CLEANUP_FAILED=79

# Backup/Archive errors (80-89)
EXIT_BACKUP_ERROR=80
EXIT_BACKUP_FAILED=81
EXIT_RESTORE_FAILED=82
EXIT_ARCHIVE_ERROR=83
EXIT_COMPRESSION_ERROR=84
EXIT_BACKUP_VERIFICATION_FAILED=85
EXIT_BACKUP_CORRUPTION=86
EXIT_BACKUP_NOT_FOUND=87
EXIT_BACKUP_INCOMPLETE=88
EXIT_RESTORE_VERIFICATION_FAILED=89

# External tool errors (90-99)
EXIT_EXTERNAL_TOOL_ERROR=90
EXIT_COMPILER_ERROR=91
EXIT_LINTER_ERROR=92
EXIT_TEST_FAILED=93
EXIT_BUILD_FAILED=94
EXIT_DEPLOYMENT_FAILED=95
EXIT_PACKAGE_ERROR=96
EXIT_VERSION_MISMATCH=97
EXIT_LICENSE_ERROR=98
EXIT_EXTERNAL_API_ERROR=99

# User/System errors (100-109)
EXIT_USER_ERROR=100
EXIT_USER_NOT_FOUND=101
EXIT_GROUP_NOT_FOUND=102
EXIT_USER_EXISTS=103
EXIT_PASSWORD_ERROR=104
EXIT_SESSION_ERROR=105
EXIT_ACCOUNT_LOCKED=106
EXIT_ACCOUNT_EXPIRED=107
EXIT_SUDO_REQUIRED=108
EXIT_SYSTEM_ERROR=109

# Application logic errors (110-124)
EXIT_LOGIC_ERROR=110
EXIT_STATE_ERROR=111
EXIT_WORKFLOW_ERROR=112
EXIT_TRANSACTION_FAILED=113
EXIT_ROLLBACK_FAILED=114
EXIT_SYNC_ERROR=115
EXIT_CONFLICT_DETECTED=116
EXIT_DEPENDENCY_CYCLE=117
EXIT_VERSION_CONFLICT=118
EXIT_FEATURE_NOT_SUPPORTED=119
EXIT_DEPRECATED_USAGE=120
EXIT_EXPERIMENTAL_FEATURE=121
EXIT_MAINTENANCE_MODE=122
EXIT_RATE_LIMIT_EXCEEDED=123
EXIT_QUOTA_LIMIT_EXCEEDED=124

# System Reserved Exit Codes (125-255)
EXIT_COMMAND_NOT_EXECUTABLE=126
EXIT_COMMAND_NOT_FOUND=127
EXIT_INVALID_EXIT_ARG=128
EXIT_FATAL_SIGNAL_BASE=128
EXIT_CTRL_C=130
EXIT_OUT_OF_RANGE=255
