#!/bin/bash
# rc.sh

# Basic return values
RETURN_SUCCESS=0
RETURN_FAILURE=1
RETURN_INVALID_ARGS=2
RETURN_NOT_IMPLEMENTED=3
RETURN_NOT_SUPPORTED=4

# Validation return values
RETURN_VALID=0
RETURN_INVALID=1
RETURN_EMPTY=2
RETURN_TOO_SHORT=3
RETURN_TOO_LONG=4
RETURN_INVALID_FORMAT=5
RETURN_INVALID_RANGE=6
RETURN_INVALID_TYPE=7

# Resource return values
RETURN_AVAILABLE=0
RETURN_NOT_FOUND=1
RETURN_EXISTS=2
RETURN_BUSY=3
RETURN_LOCKED=4
RETURN_PERMISSION_DENIED=5
RETURN_CORRUPTED=6
RETURN_EXPIRED=7

# Operation return values
RETURN_COMPLETED=0
RETURN_PARTIAL=1
RETURN_SKIPPED=2
RETURN_CANCELLED=3
RETURN_TIMEOUT=4
RETURN_RETRY_NEEDED=5
RETURN_PERMANENT_FAILURE=6
RETURN_TEMPORARY_FAILURE=7
