name: Format Shell Scripts

on:
  push:
    branches: ["shellcheck"]
  workflow_dispatch:

jobs:
  format-sh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for PR diffs

      - name: Set up shfmt
        run: |
          curl -sSLo shfmt https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin/

      - name: Format all .sh files
        run: |
          shfmt -w .

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: format shell scripts via shfmt"
          branch: shfmt-auto-format
          title: "Auto Format Shell Scripts"
          body: "This PR auto-formats all `.sh` files using [shfmt](https://github.com/mvdan/sh)."
          delete-branch: true
